version: '3.8'

services:

  app:
    build: .
    environment:
      DB_HOST: database-1.c5a0qkqs821q.eu-north-1.rds.amazonaws.com
      DB_USER: admin
      DB_PASSWORD: srinurds
      DB_NAME: pypro
    expose:
      - "8000"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app