services:

  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: srinu
      MYSQL_DATABASE: pypro
      MYSQL_USER: pyuser
      MYSQL_PASSWORD: py123
    ports:
      - "3306:3306"

  app:
    build: .
    depends_on:
      - db
    ports:
      - "5000:5000"