apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-app
  labels:
    app: incident-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: incident-app
  template:
    metadata:
      labels:
        app: incident-app
    spec:
      containers:
      - name: incident-container
        image: srinivs2201/incidentmanagement:latest
        ports:
        - containerPort: 5000